# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1437145493);
user_pref("app.update.lastUpdateTime.background-update-timer", 1437145252);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1437145613);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1437145002);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1437145373);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1437145132);
user_pref("app.update.migrated.updateDir", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.hotfix.v20150225.01.complete", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20141113143407");
user_pref("browser.slowStartup.averageTime", 4076);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20141113143407");
user_pref("browser.startup.homepage_override.mstone", "33.1.1");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4,\"bookmarks\":0}");
user_pref("browser.taskbar.lastgroupid", "308046B0AF4A39CB");
user_pref("browser.uitour.whitelist.add.260", "");
user_pref("browser.uitour.whitelist.add.340", "");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1437231281525");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1437144881525");
user_pref("datareporting.sessions.current.activeTicks", 192);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2725);
user_pref("datareporting.sessions.current.main", 46);
user_pref("datareporting.sessions.current.sessionRestored", 2870);
user_pref("datareporting.sessions.current.startTime", "1437145010632");
user_pref("datareporting.sessions.current.totalTime", 1104);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1437144878020,\"a\":8,\"t\":131,\"c\":true,\"m\":156,\"fp\":565,\"sr\":5567}");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "formhistory%40yahoo.com:1.4.0.4.1-signed,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:33.1.1");
user_pref("extensions.getAddons.cache.lastUpdate", 1437145493);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20150311.01");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1437100667201,\"rdfTime\":1415924238000}}},{\"name\":\"app-profile\",\"addons\":{\"formhistory@yahoo.com\":{\"descriptor\":\"C:\\\\Users\\\\Creep\\\\AppData\\\\Roaming\\\\Mozilla\\\\Firefox\\\\Profiles\\\\j3uv3vkf.default\\\\extensions\\\\formhistory@yahoo.com\",\"mtime\":1437145012292,\"rdfTime\":1437144912477}}}]");
user_pref("extensions.lastAppVersion", "33.1.1");
user_pref("extensions.lastPlatformVersion", "33.1.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://search/form%20history");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gecko.buildID", "20141113143407");
user_pref("gecko.mstone", "33.1.1");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1437144944);
user_pref("media.gmp-gmpopenh264.version", "1.1");
user_pref("media.gmp-manager.lastCheck", 1437144944);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 53674);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1437145010);
user_pref("toolkit.telemetry.previousBuildID", "20141113143407");
